### ISSUE TITLE
[Bug] App crashes when changing language in UI

### ISSUE THREAD

**Issue by sushidave** [minutogit/eMinuto-Desktop-Prototype#7]
### Current status
Users can change the language of the UI in the navigation menu under Start > Language > (Language name).
### Actual behaviour
The app crashes and throws this error in the terminal:
```
Traceback (most recent call last):
  File "/home/[user]/Applications/eMinuto/src/gui/qt/qt_main.py", line 1508, in change_language
  File "/home/[user]/Applications/eMinuto/src/gui/qt/qt_main.py", line 1512, in restart_application
  File "/home/[user]/Applications/eMinuto/os.py", line 542, in execl
FileNotFoundError: [Errno 2] File or directory not found
```
### Expected behaviour
UI switches to the selected language.

eMinuto version: 0.1.0
OS: Linux Ubuntu

**Comment by minutogit** [comment]
fixed
